gradle/android-cache-fix-gradle-plugin

src/main/groovy/org/gradle/android/AndroidCacheFixPlugin.groovy
src/test/groovy/org/gradle/android/PluginApplicationTest.groovy
src/test/groovy/org/gradle/android/SimpleAndroidApp.groovy

Doing so would render some of the workarounds unable to operate.
Fixes #3.

Prevent plugin from being applied in afterEvaluate block

---

src/main/groovy/org/gradle/android/AndroidCacheFixPlugin.groovy

This avoids having someone do late configuration changes and make us miss the value. This happened with Santa Tracker and processorListFile.

Use beforeTask to read original values

---

README.md
build.gradle
src/main/groovy/org/gradle/android/AndroidCacheFixPlugin.groovy
src/main/groovy/org/gradle/android/CompilerArgsProcessor.groovy
src/test/groovy/org/gradle/android/CompilerArgsProcessorTest.groovy
src/test/groovy/org/gradle/android/PluginApplicationTest.groovy
src/test/groovy/org/gradle/android/RelocationTest.groovy
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

We can now be explicit that AGP 3.2.0 does not need the cache-fix plugin anymore.

Clear up 3.2.x situation

---

build.gradle

Do not enforce Android 3.0.0 as a plugin dependency

---

src/main/groovy/org/gradle/android/workarounds/RoomSchemaLocationWorkaround.groovy

This sets the `mergeRoomSchemaLocations` as an input annotated property.
This also set the duplicate copy strategy to include duplicates.
Fixes #80

Fix deprecation warnings.

---

.travis.yml
README.md
gradle/buildScanInit.gradle
src/main/groovy/org/gradle/android/AndroidCacheFixPlugin.groovy
src/main/groovy/org/gradle/android/workarounds/AbstractAbsolutePathWorkaround.groovy
src/main/groovy/org/gradle/android/workarounds/RoomSchemaLocationWorkaround.groovy
src/main/groovy/org/gradle/android/workarounds/Workaround.groovy
src/test/groovy/org/gradle/android/RoomSchemaLocationWorkaroundTest.groovy
src/test/groovy/org/gradle/android/SimpleAndroidApp.groovy
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

Previously, the room schema workaround would not be applied when `kapt.use.worker.api=false` because this causes the kapt tasks to use a different type (`KaptWithKotlincTask`) which stores the annotation processor options differently and evaluates relative paths differently.
This fixes the workaround so that it will also work when this option is set.  It also checks the Kotlin Gradle plugin version and punts if a version < 1.3.70 is used as the annotation processor options are stored differently on earlier versions and it's more difficult/complex to handle those additional cases.  For now, we only support 1.3.70 and higher.

Make room schema workaround work with KaptWithKotlincTask

---

src/main/groovy/org/gradle/android/workarounds/RoomSchemaLocationWorkaround.groovy
src/test/groovy/org/gradle/android/RoomSchemaLocationWorkaroundTest.groovy
src/test/groovy/org/gradle/android/SimpleAndroidApp.groovy

Sometimes other annotation processors use the room schema location annotation processor argument to do further processing of schemas and expect the existing schemas to also be present (not just the newly generated schemas).  This change allows the task specific directory to be seeded with the existing schemas before starting the compilation process.

Task specific room schema dir is populated with existing schemas

---

README.md

- Replace wrong trailing backtick to have snippet copy & paste ready.
- Use double quotes everywhere for consistency.
- Use consistent indentation.

Fix syntax highlighting and improve Gradle snippet.

---

.gitignore
build.gradle
gradle/buildScanInit.gradle
src/main/groovy/org/gradle/android/workarounds/MergeJavaResourcesWorkaround.groovy
src/main/groovy/org/gradle/android/workarounds/MergeNativeLibsWorkaround.groovy
src/test/groovy/org/gradle/android/CrossVersionOutcomeAndRelocationTest.groovy
src/test/groovy/org/gradle/android/PluginApplicationTest.groovy
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

Also bump versions and add local.properties to gitignore.
The travis property is removed since the build scan plugin is now applied to the tests.

Add early support for AGP 4.1

---

build.gradle
src/main/groovy/org/gradle/android/AndroidCacheFixPlugin.groovy
src/test/groovy/org/gradle/android/PluginApplicationTest.groovy
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

There was a small bug in the logic which was causing the fixes to be applied to versions that are newer than the fixed version.
Fixes #99

Fix applying fixes to newer versions.

---

build.gradle
src/main/groovy/org/gradle/android/Versions.groovy
src/test/groovy/org/gradle/android/VersionsTest.groovy
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

The previous way of calculating the minimum supported version was always higher than beta and alpha version. This caused problems when testing alpha and beta versions in isolation.

Add support for AGP 4.2.0-alpha07

---

README.md

Otherwise, it reads like it's a version of the Android OS, which is not.

Add missing words in README

---

src/main/groovy/org/gradle/android/workarounds/RoomSchemaLocationWorkaround.groovy
src/test/groovy/org/gradle/android/RoomSchemaLocationWorkaroundTest.groovy
src/test/groovy/org/gradle/android/SimpleAndroidApp.groovy

Fixes the issue described in https://github.com/gradle/android-cache-fix-gradle-plugin/issues/135#issuecomment-770726740 where the Room workaround configuration is only partially be applied to the test compile tasks.  Configuration is now only applied to the main compile tasks.  Tests have been expanded to cover test tasks as well in order to catch these sorts of issues.

Only apply Room configuration to main compile tasks

---

build.gradle
gradle.properties
src/main/resources/META-INF/gradle-plugins/org.gradle.android.cache-fix.properties
src/test/groovy/org/gradle/android/SimpleAndroidApp.groovy

- Enable caching
- Enable parallel test execution
- Use `maven-publish` instead of `Upload` task
- Use Java toolchains to compile with JDK8

Improve the cache-fix plugin build

---

.github/workflows/ci-check.yml
build.gradle
src/main/groovy/org/gradle/android/AndroidCacheFixPlugin.groovy
src/main/groovy/org/gradle/android/workarounds/AbstractCompileLibraryResourcesWorkaround_4_2_orHigher.groovy
src/main/groovy/org/gradle/android/workarounds/CompileLibraryResourcesWorkaround_7_0.groovy
src/main/groovy/org/gradle/android/workarounds/MergeResourcesWorkaround.groovy
src/test/groovy/org/gradle/android/CrossVersionOutcomeAndRelocationTest.groovy
src/test/groovy/org/gradle/android/SimpleAndroidApp.groovy
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

Three changes here:
- 7.0.0 breaks the MergeResources workaround.  The property we manipulate to make it use absolute path sensitivity is now made immutable once the task graph has been calculated.  This means that although we can zero out the existing input before fingerprinting starts, we can't set it back to its original value after fingerprinting is finished.  I don't see a way around this, so I think we'll just need to wait for a fix to the underlying issue.
- The `inputDirectories` property for `CompileLibraryResourcesTask` has been renamed again in 7.0.0.  Luckily, its type did not change, so we can just subclass the 4.0 version of the workaround with the only difference being the name of the property.
- In 7.0.0, the hack that was in place to force `MergeNativeLibs` to execute no …

Update to latest version of 7.0.0-alpha and 4.2.0-rc01

---

src/main/groovy/org/gradle/android/workarounds/RoomSchemaLocationWorkaround.groovy

Replaced operator `=` with `.set` function call to make suggestion compatible with Kotlin DSL.

RoomSchemaLocationWorkaround: Change syntax in exception message

---

src/test/groovy/org/gradle/android/ConfigurationCachingTest.groovy
src/test/groovy/org/gradle/android/CrossVersionOutcomeAndRelocationTest.groovy
src/test/groovy/org/gradle/android/RoomSchemaLocationWorkaroundTest.groovy
src/test/groovy/org/gradle/android/SimpleAndroidApp.groovy
src/test/groovy/org/gradle/android/TestVersions.groovy

This adds tests for the newest and oldest supported kotlin versions in the `RoomSchemaLocationWorkaroundTest`.
The other relocation tests will default to the latest supported version.

Test latest kotlin version and oldest supported.

---

.github/workflows/ci-check.yml
src/main/groovy/org/gradle/android/workarounds/RoomSchemaLocationWorkaround.groovy
src/test/groovy/org/gradle/android/RoomSchemaLocationWorkaroundTest.groovy
src/test/groovy/org/gradle/android/SimpleAndroidApp.groovy

This fixes an issue where an incremental build of a single variant with a Room schema change can result in the wrong schemas being merged to the target folder.  
It also changes the way we handle JavaCompile vs Kapt handling so that it's more resilient and less likely to result in incorrect schemas being merged.

Fix issues with room schema merge

---

README.md

The AndroidBasePlugin is the correct way to determine if the Android plugin was applied. It is available since AGP 3.5
See this PR for our tests executed against this version of the README: https://github.com/gradle/android-cache-fix-gradle-plugin/pull/185

Use AndroidBasePlugin instead of deprecated BasePlugin.

---

README.md

* DexFileDependenciesTask: was made cacheable in `AGP 7.0.0-alpha05`
* CompileLibraryResourcesTask: experimental flags to fix absolute resource paths were enabled by default from `AGP 7.2-beta04`

Remove issues that have now been resolved

---

src/main/groovy/org/gradle/android/Warnings.groovy
src/main/groovy/org/gradle/android/WarningsService.groovy
src/main/groovy/org/gradle/android/workarounds/BundleLibraryClassesWorkaround.groovy
src/main/groovy/org/gradle/android/workarounds/CompileLibraryResourcesWorkaround.groovy
src/main/groovy/org/gradle/android/workarounds/MergeJavaResourcesWorkaround.groovy
src/main/groovy/org/gradle/android/workarounds/MergeNativeLibsWorkaround.groovy
src/main/groovy/org/gradle/android/workarounds/MergeSourceSetFoldersWorkaround.groovy
src/main/groovy/org/gradle/android/workarounds/StripDebugSymbolsWorkaround.groovy
src/main/groovy/org/gradle/android/workarounds/SystemPropertiesCompat.groovy
src/main/groovy/org/gradle/android/workarounds/Workaround.groovy
src/main/groovy/org/gradle/android/workarounds/ZipMergingTaskWorkaround.groovy

Note: this does not add CompileStatic for the RoomSchemaLocationWorkaround

Use CompileStatic

---

src/main/groovy/org/gradle/android/AndroidCacheFixPlugin.groovy
src/main/groovy/org/gradle/android/Warnings.groovy
src/main/groovy/org/gradle/android/workarounds/CompileLibraryResourcesWorkaround.groovy
src/test/groovy/org/gradle/android/CompileLibraryResourcesWorkaroundTest.groovy
src/test/groovy/org/gradle/android/SimpleAndroidApp.groovy

When a Kotlin script plugin is compiled, Gradle runs a nested build with the applied plugins in order to inspect/generate the type-safe accessors for the script.  When a Kotlin script plugin applies the cache-fix plugin, the plugin is applied to the nested build without inheriting the Gradle properties from the main build.  This causes the warnings from workarounds like `CompileLibraryResourcesWorkaround` to get printed to the console, even though the properties that it references are actually applied in the main project.
This fixes the issue by inhibiting warnings when we detect that we're in the nested build for generating type-safe accessors.  We detect this by just looking at the root project name, so there is of course the possibility of another project that just happens to be named …

Fix issue with spurious CompileLibraryResourcesWorkaround warnings

---

.github/workflows/build-verification.yml
.github/workflows/wrapper-upgrade-execution.yml

Separating the setup of the Gradle build tool from actual build invocation
is more idiomatic to GH Actions in general, and provides a clearer separation
of responsibilities.

Use separate "Set up Gradle" step in GHActions

---

README.md
release/changes.md
src/main/groovy/org/gradle/android/workarounds/CompileLibraryResourcesWorkaround.groovy
src/test/groovy/org/gradle/android/CompileLibraryResourcesWorkaroundTest.groovy
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

Remove CompileLibraryResourcesWorkaround in AGP 7.2.0-beta01+

---

build.gradle

The var was set to null instead of the expected 'org.gradle.android', causing the group to eventually be set with the gradle.plugin prefix.

Fix group when publishing on staging portal

---

src/main/groovy/org/gradle/android/workarounds/RoomSchemaLocationWorkaround.groovy

For some reason, Groovy sometimes doesn't find static methods while crawling the delegation tree when a class is compiled with @CompileStatic.  Making the method call fully qualified seems to fix it.  We fixed this in several places when we added `@CompileStatic` to these classes, but we missed this one.
Fixes #285

Fix issue with static method not being found sometimes with @CompileStatic

---

build.gradle

This is now done by the publish plugin itself.

Remove configuration cache compatibility line for publishPlugin task.

---

build.gradle

The new plugin-publish plugin somehow configures the test task on publishing.

Fix a failure when ZULU_ env vars are not set

---

src/main/groovy/org/gradle/android/workarounds/JdkImageWorkaround.groovy
src/test/groovy/org/gradle/android/JdkImageWorkaroundDescriptorTest.groovy

This fixes an issue in the JdkImageWorkaround where module-descriptors.txt could have different ordering for its contents due to different hashing algorithms across operating systems.  Instead of using the `toString()` method, we now serialize the module descriptor ourself and sort any unordered sets in the descriptor so that equivalent module descriptors will always serialize to the same contents.
This also fixes an issue where the runtime classpath normalization could sometimes be configured after it had been finalized.

Fix issue with ordering on serialized module descriptors

---

src/test/groovy/org/gradle/android/SimpleAndroidApp.groovy

We discovered that the tests are still building projects using jcenter, so this is a simple update to swap that out.  Hopefully all works correctly.

Replace jcenter with mavenCentral

---

src/main/groovy/org/gradle/android/workarounds/JdkImageWorkaround.groovy
src/test/groovy/org/gradle/android/JdkImageWorkaroundTest.groovy
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

The issues that this workaround explicitly addresses should be fixed in 7.4.0-alpha07 per https://issuetracker.google.com/u/1/issues/234820480.  If using different JDK versions, it's still possible that further normalization might be necessary if aligning the versions is not possible.

Don't use JdkImageWorkaround after 7.4.0-alpha07

---

src/main/groovy/org/gradle/android/workarounds/RoomSchemaLocationWorkaround.groovy
src/test/groovy/org/gradle/android/RoomSchemaLocationWorkaroundTest.groovy

Use the new variant API on AGP versions 7.4.0 and higher.
Fixes #353

Support new variant API on AGP 7.4.0 and up

---

README.md

Fixes https://github.com/gradle/android-cache-fix-gradle-plugin/issues/367

MergeResources relocateability is fixed in 8.0.0-alpha01

---

.github/workflows/build-verification.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/wrapper-upgrade-execution.yml

Deprecation warnings appear when running actions/checkout@v2, this is fixed when upgrading to actions/checkout@v3

Upgrade Github actions/checkout to v3

---

README.md
src/main/groovy/org/gradle/android/workarounds/RoomSchemaLocationWorkaround.groovy
src/test/groovy/org/gradle/android/RoomSchemaLocationWorkaroundTest.groovy
src/test/groovy/org/gradle/android/TestVersions.groovy

Drop support for Kotlin 1.5.32 in the supported Kotlin test versions for the Android Cache Fix Plugin
1.5.32 is behind three minor versions of the current one(1.8.0). Additionally, newer AGP versions bring Kotlin dependencies with incompatible binary version of its metadata: https://issuetracker.google.com/issues/241287607.
This PR sets the `MINIMUM_KOTLIN_VERSION` to Kotlin 1.6.10 to the plugin. Previous minimum version (1.4.32) it was not included in the supported test versions of Kotlin and currently is not building when using AGP 7.
Removed the additional assertions on the tests targeting lower Kotlin versions and fixed test `workaround is not applied with older Kotlin plugin version (Kotlin #kotlinVersion)` to include latest AGP version.

Set minimum Kotlin version to 1.6.10 and drop support Kotlin 1.5.32 

---

src/main/groovy/org/gradle/android/workarounds/RoomSchemaLocationWorkaround.groovy
src/test/groovy/org/gradle/android/TestVersions.groovy

Task `KaptWithKotlincTask` was removed in 1.8 because Kapt is always run via Gradle workers: https://github.com/JetBrains/kotlin/commit/b8b0b279ee2195ccbdce61e2365f123ee928532b
Added Kotlin 1.8.0 in Kotlin test supported versions for tests.
Closes #398

Fix RoomWorkaround ignoring `KaptWithKotlincTask` for  Kotlin 1.8

---

src/test/groovy/org/gradle/android/SimpleAndroidApp.groovy

In the Gradle runner test builds, we were adding always the configuration `annotationProcessor "androidx.room:room-compiler`. This configuration is not incorrect, however, in real projects we either configure the `kapt` configuration or the `annotationProcessor` for the Room compiler.
This PR separates the runtime declaration from the processor one. This change doesn't affect the RoomWorkaround for non-Kotlin projects. 
PR **doesn't** have dependency with #408

Separating the processor dependency from the runtime dependency in Gradle Runner builds

---

src/main/groovy/org/gradle/android/workarounds/room/androidvariants/ApplyAndroidVariants.groovy
src/test/groovy/org/gradle/android/PluginBlockTest.groovy
src/test/groovy/org/gradle/android/SimpleAndroidApp.groovy

Issue #412 describes the issue when using AGP 7.4 and the Plugin throws:
```
Failed to apply plugin 'org.gradle.android.cache-fix'.
> Cannot invoke method selector() on null object
```
This is caused when the plugin is configuring a project without Android plugins applied. 
I can reproduce the error when in the project `nowinandroid` I remove the `apply false` in the plugin definition. That means the rootProject is trying to retrieve the `androidComponents`:
```
def androidComponents = project.extensions.findByName("androidComponents")
```
when they are not applied. This is a change in the AGP not reproducible in 7.3.1. 
Similar to the old implementation this PR only applies the configuration when a project contains the Android plugins.

Apply configuration new variants API only when Plugins are present

---

src/main/groovy/org/gradle/android/workarounds/room/androidvariants/ApplyAndroidVariants.groovy

Based on this discussion https://github.com/gradle/android-cache-fix-gradle-plugin/pull/414#discussion_r1070514914
We configure the AGP 7.4 variants with `project.plugins.withId("com.android.base") {` instead of checking for specific plugins like application/library.

Using base plugin for Room workaround

---

src/test/groovy/org/gradle/android/JdkImageWorkaroundTest.groovy

#426, good catch @tylerbertrand 
Before
https://ge.solutions-team.gradle.com/s/tuyrjfxxl2rko/tests/overview#:testandroid8_0_0_beta01-0-org.gradle.android.jdkimageworkaroundtest-3-workaround-is-enabled-when-enabled-via-system-property-9
After
https://ge.solutions-team.gradle.com/s/zegdtyextlj46/tests/overview#:testandroid8_0_0_beta01-0-org.gradle.android.jdkimageworkaroundtest-3-workaround-is-enabled-when-enabled-via-system-property-9

Fix version assumption JDKImage

---

src/main/groovy/org/gradle/android/workarounds/room/JavaCompileWorkaround.groovy

After workaround extractions and 2.6.4, users reported #432 
This issue is reproducible when applying the plugin in modules without kapt or room implementation.
The extraction didn't verify if the schema was present like in version 2.6.3: https://github.com/gradle/android-cache-fix-gradle-plugin/blob/v2.6.3/src/main/groovy/org/gradle/android/workarounds/RoomSchemaLocationWorkaround.groovy#L259
This PR adds the check. Kapt workaround is not affected. 
Internal note: Why we don't have tests covering builds with this configuration?

Check if schema exists to avoid JavaCompileWorkaround issue

---

src/test/groovy/org/gradle/android/TestVersions.groovy

Updating the Kotlin version used for Tests. 
This is required for the `KspWorkaround` that includes the pair <Kotlin Version, Ksp Version>

Update Kotlin test version 1.8.10

---

src/test/groovy/org/gradle/android/SimpleAndroidApp.groovy

During the CI builds of the KspWorkaround(#429), we noticed builds failing in the tests executed:
Test failing showed flakiness in some of the executions:
Logs showed:
```
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
```
This error happens at the level of the test, not in the Build containing the Gradle runner builds. 
At this point, we started monitoring more in detail the number of test executed for a given build: 
For instance, for AGP 7.3.1 we execute around 40 unit tests, some of those tests execute different builds using different Kotlin versions. This combination causes to run more than 55 builds per build invocation.  We enabled process tracking for the Kotlin processes and discovered that 6 Kotlin processes were created:
We are …

Updating parameters used in gradle properties for the Kotlin daemon Simple app

---

.github/workflows/build-verification.yml
.github/workflows/wrapper-upgrade-execution.yml

As per note in the https://github.com/actions/setup-java#supported-distributions section adopt openjdk was moved to eclipse temurin and it is advised to update

Use temurin instead of adopt java distribution

---

.github/workflows/build-verification.yml
build.gradle
gradle.properties

Enable PTS unless `isPTSEnabled` property is explicitly set to false
* If `isPTSEnabled` property exists but has not been set, or has been set to `true`, PTS will be enabled.
* If `isPTSEnabled` property has been explicitly set to `false`, PTS will be disabled.
* With this PR, PTS will be disabled by default, as `isPTSEnabled` has been set to `false`
Enable PTS in CI if not running against main

Enable PTS

---

build.gradle

Signing only required in CI when taskGraph includes publishingPlugins

---

build.gradle

Resolves #437 
* This allows users to view release notes from the plugin portal and gives them an idea of what will be gained by updating to that version
* Leverage providers.fileContents() to support configuration caching when reading release notes file
* Use configuration-cache-compatible Provider.fileContents() to read version file
* Inline gitReleaseTag()
* Use githubRelease extension object to get tagName value for createReleaseTag task
* Correct githubRelease extension block indent from 3 spaces to 4

Add release notes to published plugin description and read version file using CC-comaptible api

---

README.md

After official announcement:
https://blog.gradle.org/kotlin-dsl-is-now-the-default-for-new-gradle-builds
enabling by default Kotlin DSL
closes #462

Kotlin DSL shown by default in README

---

buildSrc/build.gradle
buildSrc/settings.gradle
settings.gradle

Note that we also utilize toolchains in the SimpleAndroidApp. Enabling auto-provisioning unconditionally in the project under test causes issues with the [Gradle 7.0.2 test cases](https://ge.solutions-team.gradle.com/s/vcnnowpemgbts/tests/overview?outcome=failed). I'm exploring this separately.

Toolchains are auto-provisioned via the foojay plugin

---

.github/workflows/build-verification.yml
.github/workflows/wrapper-upgrade-execution.yml

Auto-provisioning can come with a tradeoff of slower builds when a toolchain is auto-provisioned. For our CI builds, we should disable auto-provisioning to make sure we are not taking a performance hit by provisioning toolchains on every build.

Disable toolchain provisioning in CI

---

README.md

This PR updates the text of the MergeResources cache miss to state that it has been fixed as of AGP 8.0.0.

MergeResources explanation is updated with the latest details

---

build.gradle.kts

During the kts migration, I wrongly changed:
```
def isProdPortal = !System.getProperty('gradle.portal.url')
```
by 
```
val isProdPortal = System.getProperty("gradle.portal.url") != null
```
This is causing a change in the group value when publishing the plugin in the release workflow. This pr applies the same logic

fix incorrect gav logic in the migration

---

.github/workflows/submit-github-dependency-graph.yml

This workflow will generate a dependency snapshot for the repository and upload it to the GitHub Dependency Submission API. It relies on experimental support in https://github.com/gradle/gradle-build-action.

Add workflow to submit GitHub dependency graph

---

README.md
src/test/groovy/org/gradle/android/RoomSchemaLocationKspWorkaroundTest.groovy
src/test/groovy/org/gradle/android/TestVersions.groovy

This will fix tests timing out due to taking a very long time.
Most Kotlin users are up-to-date on the latest versions.

Drop support for Kotlin 1.6

---

build.gradle.kts

It's not clear why we are using older versions of these libraries in `compileOnly` and `testImplementation` configurations. Newer versions should address some of the current security vulnerabilities.

Use latest versions of AGP for main build

---

src/main/groovy/org/gradle/android/workarounds/PackageForUnitTestWorkaround.groovy
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

AGP 8.3 has disabled caching for PackageForUnitTest tasks. Issue has been marked as fixed:
https://issuetracker.google.com/issues/292114808
This PR drops support for PackageForUnitTest workaround in AGP 8.3.
**Tests**
AGP 8.1.1: Build Cache Result --> Miss (local), Store (local) --> https://ge.solutions-team.gradle.com/s/acdqg2r7ntsww/timeline?details=p4gvuy5bywso4&type=com.android.build.gradle.internal.tasks.PackageForUnitTest
AGP 8.3.0-alpha01:  Not cacheable --> Simple merging task. -->  https://ge.solutions-team.gradle.com/s/dqo7hoygh73hg/timeline?details=p4gvuy5bywso4&type=com.android.build.gradle.internal.tasks.PackageForUnitTest

Removing support for PackageForUnitTest workaround in 8.3

---

src/main/groovy/org/gradle/android/workarounds/ZipMergingTaskWorkaround.groovy
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

This was fixed in AGP 8.1.0-alpha10
https://issuetracker.google.com/issues/272740536
Fixes #606

Add FixedIn to ZipMergingTask

---

.github/workflows/build-verification.yml

The Android SDK Platform-Tools got removed completely from the image ubuntu22/20240107.1 causing jobs failing at the step `Patch api-version` https://github.com/gradle/android-cache-fix-gradle-plugin/actions/runs/7493334606/job/20399411965
Because it's removed this PR removes the patch api step because is not required also it removes the file required for the workaround. 
Additionally, this pr updates the sdk manager references in the steps `List Android Packages` and `Accept license 34.0.0`([ref](https://github.com/actions/runner-images/issues/9146)):
`$ANDROID_HOME/tools/bin/sdkmanager` to `${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager`

Removing patch_api_version step

---

.github/workflows/build-verification.yml
.github/workflows/submit-github-dependency-graph.yml
.github/workflows/wrapper-upgrade-execution.yml
build.gradle.kts

- Replaces use of `gradle/gradle-build-action` with `gradle/actions/setup-gradle`.
- Replaces custom dependency graph workflow with simpler one using `gradle/actions/dependency-submission`.
- Fixes a reported vulnerability by upgrading transitive dependency in plugin classpath.

Use `gradle/actions/setup-gradle` and `gradle/actions/dependency-submission`

---

src/main/resources/versions.json
src/test/groovy/org/gradle/android/WorkaroundTest.groovy
src/test/resources/expectedOutcomes/8.4.0-alpha09_outcomes.json

This PR bump supported AGP version from `8.4.0-alpha08` to `8.4.0-alpha09`.

Bump supported AGP version from 8.4.0-alpha08 to 8.4.0-alpha09

---

src/main/groovy/org/gradle/android/workarounds/JdkImageWorkaround.groovy
src/test/groovy/org/gradle/android/JdkImageWorkaroundTest.groovy

#646 describes the issue when applying the plugin using not aligned JDKs in the toolchain and the build, build fails on the JdkImageWorkaround with the following message:
```
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':app:androidJdkImage'.
> Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image_extracted, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
> Execution failed for ExtractJdkImageTransform: /Users/kio/.gradle/caches/transforms-3/066939602350b840bee1b3625dbd3a64/transformed/output.
> Unsupported major.minor version 64.0
```
After syncing with the BT team, we are proposing this PR where the main change is to not use the module descriptor after …

Avoid capturing module descriptor in JdkImageWorkaround for AGP >= 8

---

README.md

Since 2.6.0-alpha02, the Room Gradle Plugin is available. But now that Room 2.6.0 (and later) are released, it would be more appropriate to point users to the documentation regarding the plugin.

Update Link to Room Gradle Plugin Docs

---

.github/workflows/build-verification.yml
.github/workflows/submit-github-dependency-graph.yml
.github/workflows/wrapper-upgrade-execution.yml
build.gradle.kts

- Migrated GitHub actions gradle executions to access token auth 
- Migrated GitHub actions maven executions env var access key to develocity naming
- Removed unused `gradle.enterprise` import

Github actions access token migration

---

.github/workflows/build-verification.yml

Recent jobs on CI builds from AGP versions were failing with:
```
java.io.IOException: Unable to create debug keystore in /home/runner/.config/.android because it is not writable.
```
There is an initial workaround to fix this problem in PR #1720. The proposed solution is valid, but while trying to understand the reason for the failure, we observed that it is caused by an attempt to write to the Android folder during the build. This occurs in a folder created by a different user (root). The original folder is created when manually installing the SDK build tool version 34.0.0(during the gha setup):
```
- name: List Android Packages
run: sudo ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --list | sed -n '/Available Packages/q;p'
- name: Accept license 34.0.0
run: echo "y" | sudo …
```

Removing manual installation build tools 34.0.0

---

.github/renovate.json5

- Always allow pre-release in `latestKnownAgpVersion` property
Default behavior would be to only allow it while it's already unstable (currently the case).
- Disable dependency dashboard (#1746)
- Migrate deprecated setting
Assuming this is the main change proposed by Renovate in #1749. It's a noisy diff there due to syntax changes.
- Group all AGP version changes in single PR
This should prevent the check failure that's currently affecting #1747 and #1748. Making them a single PR should fix that error.
These changes were tested on a fork. An example PR is gabrielfeo/android-cache-fix-gradle-plugin#12). A [help][1] build on that branch confirms that the new PR should pass the current error.
[1]: https://ge.solutions-team.gradle.com/s/hvjxrb36dfoja

Adjust Renovate config

---

.github/workflows/build-verification.yml

Since #1742, the `generate_versions` CI job [succeeds even though it can't parse the JSON file][1]. Parsing fails because `jq` [doesn't support JSON5][2]. The job succeeds silently despite this failure because it's ran inside [command substitution][3]. This currently results in #1751 not running proper tests.
Fix the `generate_versions` CI job to correctly parse the JSON5 file by stripping comment lines before passing its content to `jq`. Also ensure the job will fail if the step fails by running it once outside command substitution and ensuring `pipefail` is on. This replaces the "debug" step.
[1]: https://github.com/gradle/android-cache-fix-gradle-plugin/actions/runs/12717112831
[2]: https://github.com/jqlang/jq/issues/1571
[3]: …

Fix generate_versions job

---

.github/renovate.json5
.github/workflows/build-verification.yml
build.gradle.kts
gradle.properties
src/main/groovy/org/gradle/android/Versions.groovy
src/main/resources/versions.json

In #1742, Renovate was set up with a more usual standard `regex` matcher configuration, which is to search for versions in lines annotated with a comment `// renovate: ...`. However, the `versions.json` file is parsed by several tools which don't support JSON5 or any form of comments, namely Groovy's `json` package and `jq`. Groovy `json` required using a lenient mode (#1742), which may suppress useful validations, while `jq` required stripping the comments beforehand (#1752). Moving away from JSON5 would be a simpler solution.
Revert the `versions.json` back from JSON5 to plain JSON and change the Renovate config to match the version properties based on the fact that their values are lists, e.g. `"8.8.0": [`. Matching the version in `gradle.properties` is also simplified to no longer …

Update Renovate config to avoid JSON5

---

build.gradle.kts
gradle/libs.versions.toml

Move build versions to a version catalog so that they're properly picked up by Dependabot.

Move build versions to catalog

---

.github/dependabot.yml
gradle/libs.versions.toml

Clarifies why bumping AGP used for compiling isn't desired (#1762); prevents Dependabot from suggesting it.
Clarifies why bumping Spock to `*-groovy-4.0` versions (#1764) isn't desired. Dependabot not set to ignore these Spock versions because it's not clear how to define a Maven version range that would exclude only `2.x-groovy-4.0` versions.

Clarify why older AGP and Spock are preferred

---

build.gradle.kts

While testing the AGP9 branch, I made some changes and was surprised that the CI checks finished immediately. After reviewing the build scans, I observed that no tests were executed:
https://ge.solutions-team.gradle.com/s/xnnyxy3b32gry/tests/overview
The timeline shows that the test task has the outcome "NO-SOURCE."
This behavior is documented in the upgrading release notes:
https://docs.gradle.org/9.0.0/userguide/upgrading_major_version_9.html#test_tasks_may_no_longer_execute_expected_tests
This PR adds test class configurations for the test version tasks, and the test tasks are now executing as expected:
https://ge.solutions-team.gradle.com/s/bxi65rplucida/tests/overview

Adding test classes configuration

---

.github/workflows/wrapper-upgrade-execution.yml

This allows PRs created by the wrapperbot to trigger workflows on the pull_request trigger.

Changed wrapper bot gh token from readonly to GH_BOT_GITHUB_TOKEN

---

src/test/groovy/org/gradle/android/WorkaroundTest.groovy

Missing AGP versions in WorkaroundTest

Missing AGP versions in WorkaroundTest
