src/main/groovy/org/gradle/android/AndroidCacheFixPlugin.groovy
src/test/groovy/org/gradle/android/PluginApplicationTest.groovy
src/test/groovy/org/gradle/android/SimpleAndroidApp.groovy

Since #7 we don't rely on the order the plugin is being applied in.

Do not complain about plugin application order

---

build.gradle
src/test/groovy/org/gradle/android/RelocationTest.groovy

There are no fixes yet, only changes in task names.

Support Android plugin 3.1.0-alpha02 and 03

---

src/main/groovy/org/gradle/android/AndroidCacheFixPlugin.groovy
src/main/groovy/org/gradle/android/CompilerArgsProcessor.groovy
src/main/groovy/org/gradle/android/Workaround.groovy
src/main/groovy/org/gradle/android/WorkaroundContext.groovy
src/test/groovy/org/gradle/android/CompilerArgsProcessorTest.groovy
src/test/groovy/org/gradle/android/RelocationTest.groovy
src/test/groovy/org/gradle/android/SimpleAndroidApp.groovy
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

Fix AndroidJavaCompile.dataBindingDependencyArtifacts relocatability

---

build.gradle
src/test/groovy/org/gradle/android/RelocationTest.groovy
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

Signed-off-by: Lóránt Pintér <lorant@gradle.com>

Support Android 3.1.0-alpha07

---

build.gradle
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

Signed-off-by: Lóránt Pintér <lorant@gradle.com>

Support Android 3.1.0-alpha08

---

README.md

The name of the plugin was wrong here

Typo on Applying the plugin

---

README.md
build.gradle
src/test/groovy/org/gradle/android/CrossVersionOutcomeAndRelocationTest.groovy
src/test/groovy/org/gradle/android/PluginApplicationTest.groovy

Update to 4.1.0-beta01

---

src/main/groovy/org/gradle/android/AndroidCacheFixPlugin.groovy
src/main/groovy/org/gradle/android/workarounds/CompileLibraryResourcesWorkaround.groovy
src/test/groovy/org/gradle/android/CrossVersionOutcomeAndRelocationTest.groovy
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

This is a regression from AGP 3.6.
Fixes #97

Fix CompileLibraryResources cache miss.

---

build.gradle

Reconfigures the buildscripts to use the plugins block as well as task configuration avoidance.

Task avoidance and plugins block

---

src/main/groovy/org/gradle/android/AndroidCacheFixPlugin.groovy
src/main/groovy/org/gradle/android/workarounds/DexFileDependenciesWorkaround.groovy
src/test/groovy/org/gradle/android/CrossVersionOutcomeAndRelocationTest.groovy
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

Make DexFileDependencies cacheable

---

src/main/groovy/org/gradle/android/workarounds/CompilerArgsProcessor.groovy
src/test/groovy/org/gradle/android/TaskAvoidanceTest.groovy

Avoid configuring JavaCompile tasks eagerly.

---

src/main/groovy/org/gradle/android/AndroidCacheFixPlugin.groovy
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

Relates to #101. There might be others but this was the only one in our project's report

Use systemProperty on Gradle 6.1 or newer

---

README.md
build.gradle
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

Support 4.2.0-beta03

---

build.gradle

Use task configuraiton avoidance.

Add stricter plugin validation.

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

Update to Gradle 7.0

---

src/main/groovy/org/gradle/android/workarounds/AbstractCompileLibraryResourcesWorkaround_4_2_orHigher.groovy
src/test/groovy/org/gradle/android/RerunTasksTest.groovy
src/test/groovy/org/gradle/android/SimpleAndroidApp.groovy

Fix bug when calling `--rerun-tasks` with configuration cache enabled.

---

README.md
build.gradle
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

https://twitter.com/AGPVersions/status/1420421375890763783

Support AGP 7.0.0

---

README.md

Check the sample here https://github.com/gradle/android-cache-fix-gradle-plugin/tree/no/apply-conventions#applying-the-plugin

Add conventions plugin sample to apply cache fix plugin.

---

.github/workflows/ci-check.yml
README.md
settings.gradle

Cleans up the Github action workflow comments
* Updates to checkout v2 and java v2
* Adds step names
* Use java 11 for tests (java 8 is no longer required)

Clean up Github Action workflow

---

build.gradle

Simplify groovy setup.

---

src/main/groovy/org/gradle/android/workarounds/JdkImageWorkaround.groovy
src/main/groovy/org/gradle/android/workarounds/SystemPropertiesCompat.groovy
src/test/groovy/org/gradle/android/JdkImageWorkaroundTest.groovy

Fixes #307 
All of our tests for this workaround rely on a toolchain being set - this failure occurs when a toolchain is not set.

Fix issue with jdkImageWorkaround and no toolchain

---

README.md

Update Readme latest version published

Update Readme 2.5.6

---

release/changes.md
src/main/groovy/org/gradle/android/workarounds/RoomSchemaLocationWorkaround.groovy
src/test/groovy/org/gradle/android/RoomSchemaLocationWorkaroundTest.groovy

Implements the ability to suppress RoomSchemaLocationWorkaround workarounds

Allow RoomSchemaLocationWorkaround to be disabled

---

src/main/groovy/org/gradle/android/workarounds/RoomSchemaLocationWorkaround.groovy

Convert println to log.info

---

src/main/groovy/org/gradle/android/AndroidCacheFixPlugin.groovy
src/test/groovy/org/gradle/android/PluginApplicationTest.groovy

Suggest updating plugin when current AGP version is not supported

---

.github/workflows/build-verification.yml
.github/workflows/wrapper-upgrade-execution.yml

Update some Github actions and remove ::set-output to get rid of deprecation warnings

Update some Github actions and remove ::set-output

---

src/main/groovy/org/gradle/android/workarounds/JdkImageWorkaround.groovy
src/test/groovy/org/gradle/android/JdkImageWorkaroundTest.groovy

Apply jdkImage workaround to unit test variants

Apply jdkImage workaround to unit test variants

---

README.md
release/changes.md

Prepare for 2.6.1 release

---

src/main/groovy/org/gradle/android/workarounds/RoomSchemaLocationWorkaround.groovy
src/main/groovy/org/gradle/android/workarounds/room/AnnotationProcessorWorkaround.groovy
src/main/groovy/org/gradle/android/workarounds/room/JavaCompileWorkaround.groovy
src/main/groovy/org/gradle/android/workarounds/room/KaptWorkaround.groovy
src/main/groovy/org/gradle/android/workarounds/room/KotlinVersion.groovy

Extracting workaround logic for Kapt and Java in the `RoomWorkaround`

Extracting Kapt/Java Workaround from main class

---

.github/workflows/build-verification.yml
build.gradle
gradle.properties

Conditionally enable PTS for all tests if the project property 'isPTSEnabled' evaluates to true
Enable PTS for all tests in CI if not running against main

Enable PTS

---

src/test/groovy/org/gradle/android/TestVersions.groovy

Update Kotlin/Ksp supported versions in tests

Update Kotlin/Ksp supported versions in tests

---

src/main/groovy/org/gradle/android/AndroidCacheFixPlugin.groovy
src/main/groovy/org/gradle/android/workarounds/PackageForUnitTestWorkaround.groovy
src/test/groovy/org/gradle/android/WorkaroundTest.groovy

Disable caching for PackageForUnitTest

---

.github/workflows/build-verification.yml
.github/workflows/wrapper-upgrade-execution.yml
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/CreateGitTag.kt
gradle.properties
settings.gradle.kts

- Clean up build logic.
- Migrates `CreateGitTag` from Groovy to Kotlin.
- Polish flags, some of them are the default, ~~and seem we can enable `configureondemand`?~~
- Use build-tools 34.0 on CI.

Minor tweaks
